sudo: required
services:
  - docker

before_install:
  - docker build -t fariaszar/docker-react-project-new -f Dockerfile.dev .

script:
  - docker run fariaszar/docker-react-project-new npm run test -- --coverage